//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTime.Models
{
    using System;
    using System.Collections.Generic;

    public partial class SERVICEPROVIDER : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICEPROVIDER()
        {
            this.PROGRAMs = new HashSet<PROGRAM>();
        }
    
        public decimal ID { get; set; }
        public string TYPE { get; set; }
        public string COMPANYNAME { get; set; }
        public string CONTACTNAME { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string MOREINFO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRAM> PROGRAMs { get; set; }
    }
}
