//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTime.Models
{
    using System;
    using System.Collections.Generic;

    public partial class TICKET : EntityBase
    {
        public decimal TICKET_ID { get; set; }
        public Nullable<decimal> CUSTOMER_ID { get; set; }
        public decimal TOUR_ID { get; set; }
        public Nullable<int> SEETNO { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual TOUR TOUR { get; set; }

        public override decimal getId()
        {
            throw new NotImplementedException();
        }
    }
}
