//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTime.Models
{
    using System;
    using System.Collections.Generic;

    public partial class TOUR : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.TICKETs = new HashSet<TICKET>();
            this.TOURORDERs = new HashSet<TOURORDER>();
            this.DRIVERs = new HashSet<DRIVER>();
            this.GUIDERs = new HashSet<GUIDER>();
        }
    
        public decimal ID { get; set; }
        public decimal DEPARTURE_ID { get; set; }
        public decimal PROGRAM_ID { get; set; }
        public decimal DESTINATION_ID { get; set; }
        public Nullable<decimal> TRANS_ID { get; set; }
        public Nullable<System.DateTime> FROM { get; set; }
        public Nullable<System.DateTime> TO { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<double> PRICE { get; set; }
    
        public virtual DEPARTURE DEPARTURE { get; set; }
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual PROGRAM PROGRAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKETs { get; set; }
        public virtual TRANSPORT TRANSPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOURORDER> TOURORDERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRIVER> DRIVERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIDER> GUIDERs { get; set; }
    }
}
