//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTime.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelTimeEDM_Entities : DbContext
    {
        public TravelTimeEDM_Entities()
            : base("name=TravelTimeEDM_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<DEPARTURE> DEPARTUREs { get; set; }
        public virtual DbSet<DESTINATION> DESTINATIONs { get; set; }
        public virtual DbSet<DRIVER> DRIVERs { get; set; }
        public virtual DbSet<GUIDER> GUIDERs { get; set; }
        public virtual DbSet<PROGRAM> PROGRAMs { get; set; }
        public virtual DbSet<SERVICEPROVIDER> SERVICEPROVIDERs { get; set; }
        public virtual DbSet<TICKET> TICKETs { get; set; }
        public virtual DbSet<TOURORDER> TOURORDERs { get; set; }
        public virtual DbSet<TRANSPORT> TRANSPORTs { get; set; }
        public virtual DbSet<TOUR> TOURs { get; set; }
    }
}
